### ISSUE TITLE
how do I use this?

### ISSUE THREAD

**Issue by erikLundstedt** [mbober1/RPi-Pico-SSD1306-library#1]
there is no CMakeLists.txt to refer to so i have no idea on how to use it

I`m a c/c++ noob but so are most other peapole that are coming from Arduino

**Comment by mbober1** [comment]
I recommend you to make two directories in the root project folder. For example "Src" and "Inc". Then in main CMakeList should you add line `add_subdirectory(Src)`. In Src you have also CMakeList file whitch should contain

```
cmake_minimum_required(VERSION 3.12)

target_sources(main
    PUBLIC
        ${CMAKE_CURRENT_LIST_DIR}/SSD1306.cpp
        ${CMAKE_CURRENT_LIST_DIR}/GFX.cpp
)

target_include_directories(main
    PUBLIC
        ${PROJECT_SOURCE_DIR}/Inc
)
```

That's it. This allows you to easily add additional libraries to your project. Cpp files to Src, Headers files to Inc.

**Comment by mbober1** [comment]
```
.
├── CMakeLists.txt
├── Inc
│   ├── font.hpp
│   ├── GFX.hpp
│   ├── logo.hpp
│   └── SSD1306.hpp
├── main.cpp
├── pico_sdk_import.cmake
├── rp2040.svd
└── Src
    ├── CMakeLists.txt
    ├── GFX.cpp
    └── SSD1306.cpp
```

**Comment by erikLundstedt** [comment]
> ```
> cmake_minimum_required(VERSION 3.12)
> 
> target_sources(main
>     PUBLIC
>         ${CMAKE_CURRENT_LIST_DIR}/SSD1306.cpp
>         ${CMAKE_CURRENT_LIST_DIR}/GFX.cpp
> )
> 
> target_include_directories(main
>     PUBLIC
>         ${PROJECT_SOURCE_DIR}/Inc
> )
> ```


is this before or after `pico_sdk_init` and `project()`

**Comment by erikLundstedt** [comment]
one thing that would be great is if you could add a /exaples/logoAndText directory were you put a "working" or "full" version of the example in the README.md




this is a common thing in the world of Arduino libraries that I've found helps (at least me) a lot

**Comment by erikLundstedt** [comment]
I also wonder if this library would work on other,similar displays(like the SH1106 display)


I might be able to test it with that display, provided that you think it might work

**Comment by erikLundstedt** [comment]
> ```
> .
> ├── CMakeLists.txt
> ├── Inc
> │   ├── font.hpp
> │   ├── GFX.hpp
> │   ├── logo.hpp
> │   └── SSD1306.hpp
> ├── main.cpp
> ├── pico_sdk_import.cmake
> ├── rp2040.svd
> └── Src
>     ├── CMakeLists.txt
>     ├── GFX.cpp
>     └── SSD1306.cpp
> ```

what is the content of 
```
 └── Src
     ├── CMakeLists.txt
```
?

**Comment by mbober1** [comment]
> > ```
> > cmake_minimum_required(VERSION 3.12)
> > 
> > target_sources(main
> >     PUBLIC
> >         ${CMAKE_CURRENT_LIST_DIR}/SSD1306.cpp
> >         ${CMAKE_CURRENT_LIST_DIR}/GFX.cpp
> > )
> > 
> > target_include_directories(main
> >     PUBLIC
> >         ${PROJECT_SOURCE_DIR}/Inc
> > )
> > ```
> 
> is this before or after `pico_sdk_init` and `project()`

This is in a different file. Look at the file tree.

**Comment by mbober1** [comment]
> one thing that would be great is if you could add a /exaples/logoAndText directory were you put a "working" or "full" version of the example in the README.md
> 
> this is a common thing in the world of Arduino libraries that I've found helps (at least me) a lot

I'll consider that

**Comment by mbober1** [comment]
> I also wonder if this library would work on other,similar displays(like the SH1106 display)
> 
> I might be able to test it with that display, provided that you think it might work

SH1106 is bit diffrent. The last few days I was working on the library for SH1106 but not everything is working yet.

**Comment by mbober1** [comment]
> > ```
> > .
> > ├── CMakeLists.txt
> > ├── Inc
> > │   ├── font.hpp
> > │   ├── GFX.hpp
> > │   ├── logo.hpp
> > │   └── SSD1306.hpp
> > ├── main.cpp
> > ├── pico_sdk_import.cmake
> > ├── rp2040.svd
> > └── Src
> >     ├── CMakeLists.txt
> >     ├── GFX.cpp
> >     └── SSD1306.cpp
> > ```
> 
> what is the content of
> 
> ```
>  └── Src
>      ├── CMakeLists.txt
> ```
> 
> ?

```
cmake_minimum_required(VERSION 3.12)

target_sources(main
    PUBLIC
        ${CMAKE_CURRENT_LIST_DIR}/SSD1306.cpp
        ${CMAKE_CURRENT_LIST_DIR}/GFX.cpp
)

target_include_directories(main
    PUBLIC
        ${PROJECT_SOURCE_DIR}/Inc
)
```

**Comment by erikLundstedt** [comment]
fatal error: GFX.hpp: No such file or directory
 #include "GFX.hpp"
```
 .
├── build
│   ├── stuff like makefile here, removed for easy posting
├── CMakeLists.txt
├── inc
│   ├── font.hpp
│   ├── GFX.hpp
│   ├── logo.hpp
│   └── SSD1306.hpp
├── main.cpp
├── pico_sdk_import.cmake
└── src
    ├── CMakeLists.txt
    ├── GFX.cpp
    └── SSD1306.cpp
```

**Comment by mbober1** [comment]
I added an example of use. Hope it's clear now.

**Comment by erikLundstedt** [comment]
> I added an example of use. Hope it's clear now.

thank you very much!
and good luck with getting the SH1106 to work
