### ISSUE TITLE
Height pixels divided by 2

### ISSUE THREAD

**Issue by cvtvoogt** [mbober1/RPi-Pico-SSD1306-library#2]
I have a RPi Pico and a [I2C 0.91" oled 128x32](https://www.aliexpress.com/item/32879702750.html?spm=a2g0o.productlist.0.0.57a1461cBtumO3&algo_pvid=9fab1f77-bde2-4f9a-a210-af38b682b8f0&algo_expid=9fab1f77-bde2-4f9a-a210-af38b682b8f0-0&btsid=0b0a050116190714117753595e99a7&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_) display. 

With this code the result is a reactangle of 10x5 instead of 10x10 (see image). The second block exceed the vertical no of pixels. Counting the shown vertical pixel it are 16 instead of 32. 
```
    i2c_init(i2c1, 100000);
    gpio_set_function(2, GPIO_FUNC_I2C);
    gpio_set_function(3, GPIO_FUNC_I2C);
    gpio_pull_up(2);
    gpio_pull_up(3);

    GFX oled(0x3C, 128, 32, i2c1);
    oled.clear();
    oled.drawFillRectangle(0, 0, oled.getWidth(), oled.getHeight(), colors::BLACK);
    oled.drawFillRectangle(0, 0, 10, 10, colors::WHITE);
    oled.drawFillRectangle(5, 20, 20, 20, colors::WHITE);
    oled.display();
```
![S20210422_0002](https://user-images.githubusercontent.com/21263986/115664894-c698be00-a342-11eb-90f7-9ba86e99eb8e.jpg)

When I define the height as 64 I get an actual height of 32.
```
    GFX oled(0x3C, 128, 64, i2c1);
    oled.clear();
    oled.drawFillRectangle(0, 0, oled.getWidth(), oled.getHeight(), colors::BLACK);
    oled.drawFillRectangle(0, 0, 10, 10, colors::WHITE);
    oled.drawFillRectangle(5, 20, 20, 20, colors::WHITE);
    oled.drawFillRectangle(0, 20, 5, 30, colors::WHITE);
    oled.display();
```
![S20210422_0003](https://user-images.githubusercontent.com/21263986/115665553-bdf4b780-a343-11eb-9901-6756b6d4558c.jpg)

With an Arduino it works perfectly. Has any one an idea about the course/solution?

**Comment by mbober1** [comment]
Hi! I haven't tested this library on screen other than 128x64. Thank you for this issue, i will try to fix it.

**Comment by mbober1** [comment]
128x32 screens should work by now. Test it and let me know if everything is ok.

**Comment by cvtvoogt** [comment]
Hi, The problem is solved. Thanks.

![S20210422_0002](https://user-images.githubusercontent.com/21263986/115776601-9853c680-a3b4-11eb-9d35-46cde44783b2.jpg)

**Comment by mbober1** [comment]
Nice to hear it! I have some more advice for you.
1. Try increasing the speed from 100kHz to 400kHz. Most displays can handle it.
2. You don't need to fill the entire screen with a black rectangle to clear it. The clear() function does just that, and should work faster. You can even fill the entire screen white with clear(colors::WHITE). I have added descriptions to the functions to make them clearer. Good luck!
